//----------------Data that would come from a database---------------------
    const jobData =  [
        {
            "Job Title": "Senior Android Developer",
            "Time": "4 hours ago",
            "Date Published": "10/3/22",
            "Job Type": "Temporary",
            "Company Name": "Bounteous",
            "Contingency": "Yes",
            "Location Full": "Mexico ; Mexico-Remote ;",
            "URL": "https://www.bounteous.com",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "1"
        },
        {
            "Job Title": "Security Architect",
            "Time": "9 hours ago",
            "Date Published": "10/3/22",
            "Job Type": "Full Time",
            "Company Name": "American Tower Corporation",
            "Contingency": "No",
            "Location Full": "MA-Other ;",
            "URL": "https://www.americantower.com/",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "2"
        },
        {
            "Job Title": "Software Engineer (L5) - AVTnT (Audio Video Test & Tools)",
            "Time": "3 days ago",
            "Date Published": "9/30/22",
            "Job Type": "Full Time",
            "Company Name": "Netflix",
            "Contingency": "No",
            "Location Full": "CA-Other ;",
            "URL": "https://jobs.netflix.com/?utm_campaign=LIHomePage&utm_source=linkedin",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "3"
        },
        {
            "Job Title": "Sr Mobile UX/UI Designer",
            "Time": "3 days ago",
            "Date Published": "9/30/22",
            "Job Type": "Internship",
            "Company Name": "Charles Schwab",
            "Contingency": "No",
            "Location Full": "AZ-Phoenix ; CA-San Francisco ; FL-Orlando ; IL-Chicago ; IN-Indianapolis ; MI-Other ; MO-St. Louis ; NJ-Jersey City ; TX-Austin ; TX-Dallas ;",
            "URL": "https://jobs.schwabjobs.com/",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Design",
            "Functional Area Slug": "design",
            "id": "4"
        },
        {
            "Job Title": "Project Manager",
            "Time": "3 days ago",
            "Date Published": "9/30/22",
            "Job Type": "Full Time",
            "Company Name": "Charles Schwab",
            "Contingency": "No",
            "Location Full": "CO-Denver ; TX-Austin ; TX-Dallas ;",
            "URL": "https://jobs.schwabjobs.com/",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Project Management",
            "Functional Area Slug": "project-management",
            "id": "5"
        },
        {
            "Job Title": "Software Engineering Manager",
            "Time": "3 days ago",
            "Date Published": "9/30/22",
            "Job Type": "Full Time",
            "Company Name": "Latinas in Tech",
            "Contingency": "No",
            "Location Full": "TX-Austin ; TX-Dallas ;",
            "URL": "https://jobs.schwabjobs.com/",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "6"
        },
        {
            "Job Title": "Product Owner",
            "Time": "3 days ago",
            "Date Published": "9/30/22",
            "Job Type": "Full Time",
            "Company Name": "Charles Schwab",
            "Contingency": "No",
            "Location Full": "Remote ; AZ-Phoenix ; CA-San Francisco ; CO-Denver ; IL-Chicago ; TX-Austin ; TX-Dallas ;",
            "URL": "https://jobs.schwabjobs.com/",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Other",
            "Functional Area Slug": "zother",
            "id": "7"
        },
        {
            "Job Title": "LAC Software Engineering Manager",
            "Time": "3 days ago",
            "Date Published": "9/30/22",
            "Job Type": "Full Time",
            "Company Name": "Qualtrics",
            "Contingency": "No",
            "Location Full": "Mexico ;",
            "URL": "http://qualtrics.com",
            "Perks": "remotefriendly ; paidparentalleave ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "8"
        },
        {
            "Job Title": "Database Administrator",
            "Time": "4 days ago",
            "Date Published": "9/29/22",
            "Job Type": "Full Time",
            "Company Name": "Wikimedia Foundation",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "http://wikimediafoundation.org",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "9"
        },
        {
            "Job Title": "Senior Manager, Site Reliability Engineering",
            "Time": "4 days ago",
            "Date Published": "9/29/22",
            "Job Type": "Full Time",
            "Company Name": "Wikimedia Foundation",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://wikimediafoundation.org/",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "10"
        },
        {
            "Job Title": "Senior Product Manager, Platform",
            "Time": "4 days ago",
            "Date Published": "9/29/22",
            "Job Type": "Full Time",
            "Company Name": "Wikimedia Foundation",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://wikimediafoundation.org/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Product",
            "Functional Area Slug": "product",
            "id": "11"
        },
        {
            "Job Title": "Staff Site Reliability Engineer (Traffic)",
            "Time": "4 days ago",
            "Date Published": "9/29/22",
            "Job Type": "Full Time",
            "Company Name": "Wikimedia Foundation",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://wikimediafoundation.org/",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "12"
        },
        {
            "Job Title": "Senior Software Engineer - Structured Data",
            "Time": "4 days ago",
            "Date Published": "9/29/22",
            "Job Type": "Full Time",
            "Company Name": "Wikimedia Foundation",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://wikimediafoundation.org/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "13"
        },
        {
            "Job Title": "Platform Engineering Manager",
            "Time": "4 days ago",
            "Date Published": "9/29/22",
            "Job Type": "Full Time",
            "Company Name": "Honeycomb.io",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://www.honeycomb.io/",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ;",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "14"
        },
        {
            "Job Title": "Principal Software Engineer",
            "Time": "4 days ago",
            "Date Published": "9/29/22",
            "Job Type": "Full Time",
            "Company Name": "Nike",
            "Contingency": "No",
            "Location Full": "OR-Portland ;",
            "URL": "http://jobs.nike.com",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "15"
        },
        {
            "Job Title": "Principal Data Engineer",
            "Time": "4 days ago",
            "Date Published": "9/29/22",
            "Job Type": "Temporary",
            "Company Name": "Nike",
            "Contingency": "Yes",
            "Location Full": "Remote ;",
            "URL": "http://jobs.nike.com",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "16"
        },
        {
            "Job Title": "Director of Engineering - AI/ML Technology Foundation",
            "Time": "4 days ago",
            "Date Published": "9/29/22",
            "Job Type": "Freelance",
            "Company Name": "Nike",
            "Contingency": "Yes",
            "Location Full": "Remote ;",
            "URL": "http://jobs.nike.com",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "17"
        },
        {
            "Job Title": "Lead Analyst",
            "Time": "5 days ago",
            "Date Published": "9/28/22",
            "Job Type": "Full Time",
            "Company Name": "Federal Reserve Bank of San Francisco",
            "Contingency": "No",
            "Location Full": "CA-San Francisco ;",
            "URL": "https://www.frbsf.org/our-district/careers/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Project Management",
            "Functional Area Slug": "project-management",
            "id": "18"
        },
        {
            "Job Title": "Sr. Solution Architect",
            "Time": "5 days ago",
            "Date Published": "9/28/22",
            "Job Type": "Full Time",
            "Company Name": "Federal Reserve Bank of San Francisco",
            "Contingency": "No",
            "Location Full": "CA-San Francisco ;",
            "URL": "https://www.frbsf.org/our-district/careers/",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "19"
        },
        {
            "Job Title": "Sr .Net Developer w/ AWS experience",
            "Time": "5 days ago",
            "Date Published": "9/28/22",
            "Job Type": "Full Time",
            "Company Name": "Federal Reserve Bank of San Francisco",
            "Contingency": "No",
            "Location Full": "CA-San Francisco ;",
            "URL": "https://www.frbsf.org/our-district/careers/",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "20"
        },
        {
            "Job Title": "Senior Policy Admin & Billing Developer",
            "Time": "5 days ago",
            "Date Published": "9/28/22",
            "Job Type": "Internship",
            "Company Name": "State Compensation Insurance Fund",
            "Contingency": "No",
            "Location Full": "CA-Other ;",
            "URL": "http://statefundca.com",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "21"
        },
        {
            "Job Title": "Data Integration Specialist",
            "Time": "5 days ago",
            "Date Published": "9/28/22",
            "Job Type": "Full Time",
            "Company Name": "Black Knight",
            "Contingency": "No",
            "Location Full": "Remote ; Hybrid ;",
            "URL": "https://blackknight.wd1.myworkdayjobs.com/BKC/0/refreshFacet/318c8bb6f553100021d223d9780d30be",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Data & Analytics",
            "Functional Area Slug": "data-analytics",
            "id": "22"
        },
        {
            "Job Title": "Director of Marketing Operations",
            "Time": "5 days ago",
            "Date Published": "9/28/22",
            "Job Type": "Internship",
            "Company Name": "Lattice",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://lattice.com/",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "Marketing",
            "Functional Area Slug": "marketing",
            "id": "23"
        },
        {
            "Job Title": "Vice President, Product and Segment Marketing",
            "Time": "5 days ago",
            "Date Published": "9/28/22",
            "Job Type": "Full Time",
            "Company Name": "Lattice",
            "Contingency": "No",
            "Location Full": "Remote ; CA-San Francisco ;",
            "URL": "https://lattice.com/",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "Marketing",
            "Functional Area Slug": "marketing",
            "id": "24"
        },
        {
            "Job Title": "Product Manager",
            "Time": "6 days ago",
            "Date Published": "9/27/22",
            "Job Type": "Freelance",
            "Company Name": "Firemon",
            "Contingency": "Yes",
            "Location Full": "Remote ;",
            "URL": "https://www.firemon.com",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Product",
            "Functional Area Slug": "product",
            "id": "25"
        },
        {
            "Job Title": "Software Development Engineer",
            "Time": "6 days ago",
            "Date Published": "9/27/22",
            "Job Type": "Full Time",
            "Company Name": "Amazon",
            "Contingency": "No",
            "Location Full": "TN-Nashville ; TX-Austin ; WA-Seattle ;",
            "URL": "https://www.amazon.jobs/en/jobs/2229899/software-development-engineer",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "26"
        },
        {
            "Job Title": "Software Engineer III - Web Team",
            "Time": "7 days ago",
            "Date Published": "9/27/22",
            "Job Type": "Full Time",
            "Company Name": "Wikimedia Foundation",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://wikimediafoundation.org/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Product",
            "Functional Area Slug": "product",
            "id": "27"
        },
        {
            "Job Title": "Technical Project Manager - Google Analytics/Digital Analytics",
            "Time": "1 week ago",
            "Date Published": "9/26/22",
            "Job Type": "Full Time",
            "Company Name": "InfoTrust",
            "Contingency": "No",
            "Location Full": "Remote ; US ;",
            "URL": "https://infotrust.com/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Other",
            "Functional Area Slug": "zother",
            "id": "28"
        },
        {
            "Job Title": "Lead Counsel",
            "Time": "1 week ago",
            "Date Published": "9/23/22",
            "Job Type": "Temporary",
            "Company Name": "Wikimedia Foundation",
            "Contingency": "Yes",
            "Location Full": "Remote ;",
            "URL": "https://wikimediafoundation.org/",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Legal",
            "Functional Area Slug": "legal",
            "id": "29"
        },
        {
            "Job Title": "Director of Product Management, Growth and Adoption",
            "Time": "1 week ago",
            "Date Published": "9/23/22",
            "Job Type": "Full Time",
            "Company Name": "Asana",
            "Contingency": "No",
            "Location Full": "CA-San Francisco ;",
            "URL": "https://boards.greenhouse.io/asana?gh_src=77d2661c1us",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "Product",
            "Functional Area Slug": "product",
            "id": "30"
        },
        {
            "Job Title": "Director of Product Management, Orchestrate",
            "Time": "1 week ago",
            "Date Published": "9/23/22",
            "Job Type": "Full Time",
            "Company Name": "Asana",
            "Contingency": "No",
            "Location Full": "CA-San Francisco ;",
            "URL": "https://boards.greenhouse.io/asana?gh_src=77d2661c1us",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Product",
            "Functional Area Slug": "product",
            "id": "31"
        },
        {
            "Job Title": "Marketing Operations Manager",
            "Time": "1 week ago",
            "Date Published": "9/23/22",
            "Job Type": "Internship",
            "Company Name": "Chronosphere",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://chronosphere.io/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Marketing",
            "Functional Area Slug": "marketing",
            "id": "32"
        },
        {
            "Job Title": "Website Marketing Manager",
            "Time": "1 week ago",
            "Date Published": "9/23/22",
            "Job Type": "Internship",
            "Company Name": "Chronosphere",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://chronosphere.io/",
            "Seniority": "Junior Level",
            "Seniority slug": "entry-level",
            "Functional Area": "Marketing",
            "Functional Area Slug": "marketing",
            "id": "33"
        },
        {
            "Job Title": "Product Marketing Manager",
            "Time": "1 week ago",
            "Date Published": "9/23/22",
            "Job Type": "Full Time",
            "Company Name": "Chronosphere",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://chronosphere.io/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Marketing",
            "Functional Area Slug": "marketing",
            "id": "34"
        },
        {
            "Job Title": "Data Visualization Specialist (Contract)",
            "Time": "2 weeks ago",
            "Date Published": "9/22/22",
            "Job Type": "Full Time",
            "Company Name": "Wikimedia Foundation",
            "Contingency": "No",
            "Location Full": "Remote ; US ;",
            "URL": "https://wikimediafoundation.org/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Data & Analytics",
            "Functional Area Slug": "data-analytics",
            "id": "35"
        },
        {
            "Job Title": "Systems Software Engineer (E4) - Device Platform Infrastructure",
            "Time": "2 weeks ago",
            "Date Published": "9/22/22",
            "Job Type": "Full Time",
            "Company Name": "Netflix",
            "Contingency": "No",
            "Location Full": "CA-Other ;",
            "URL": "https://jobs.netflix.com/?utm_campaign=LIHomePage&utm_source=linkedin",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "36"
        },
        {
            "Job Title": "Remote Senior .NET Developer",
            "Time": "2 weeks ago",
            "Date Published": "9/21/22",
            "Job Type": "Full Time",
            "Company Name": "Charles Schwab",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://jobs.schwabjobs.com/",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "37"
        },
        {
            "Job Title": "Senior DLP Engineer",
            "Time": "2 weeks ago",
            "Date Published": "9/21/22",
            "Job Type": "Freelance",
            "Company Name": "Charles Schwab",
            "Contingency": "Yes",
            "Location Full": "Remote ;",
            "URL": "https://jobs.schwabjobs.com/",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "38"
        },
        {
            "Job Title": "Senior Product Manager",
            "Time": "2 weeks ago",
            "Date Published": "9/21/22",
            "Job Type": "Full Time",
            "Company Name": "Orum.io",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://orum.io/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Product",
            "Functional Area Slug": "product",
            "id": "39"
        },
        {
            "Job Title": "Member of Technical Staff 2",
            "Time": "2 weeks ago",
            "Date Published": "9/21/22",
            "Job Type": "Full Time",
            "Company Name": "VMWare",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "http://www.vmware.com",
            "Seniority": "Junior Level",
            "Seniority slug": "entry-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "40"
        },
        {
            "Job Title": "Principal, Responsible Technology",
            "Time": "2 weeks ago",
            "Date Published": "9/21/22",
            "Job Type": "Full Time",
            "Company Name": "Omidyar Network",
            "Contingency": "No",
            "Location Full": "Hybrid ; CA-San Francisco ; CA-Other ; DC-Washington ; DC-Other ; MD-Baltimore ; MD-Other ; NY-New York City ; NY-Other ; VA-Arlington ; VA-Other ;",
            "URL": "https://omidyar.com/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Business Strategy",
            "Functional Area Slug": "business-strategy",
            "id": "41"
        },
        {
            "Job Title": "Engineering Lead Manager",
            "Time": "2 weeks ago",
            "Date Published": "9/20/22",
            "Job Type": "Full Time",
            "Company Name": "GFiber",
            "Contingency": "No",
            "Location Full": "TN-Nashville ;",
            "URL": "https://fiber.google.com/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Operations",
            "Functional Area Slug": "operations",
            "id": "42"
        },
        {
            "Job Title": "Senior Product Engineer",
            "Time": "2 weeks ago",
            "Date Published": "9/20/22",
            "Job Type": "Full Time",
            "Company Name": "Honeycomb.io",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://www.honeycomb.io/",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "43"
        },
        {
            "Job Title": "Manager, Partnership Success",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Freelance",
            "Company Name": "SoFi",
            "Contingency": "Yes",
            "Location Full": "CA-San Francisco ; UT-Salt Lake City ; WA-Seattle ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Business Dev / Partnerships",
            "Functional Area Slug": "business-dev-partnerships",
            "id": "44"
        },
        {
            "Job Title": "Sr. Data Scientist (Relay)",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Freelance",
            "Company Name": "SoFi",
            "Contingency": "Yes",
            "Location Full": "Remote ; CA-San Francisco ; NY-New York City ; UT-Other ; WA-Seattle ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Data & Analytics",
            "Functional Area Slug": "data-analytics",
            "id": "45"
        },
        {
            "Job Title": "Senior Software Engineer",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Full Time",
            "Company Name": "SoFi",
            "Contingency": "No",
            "Location Full": "UT-Other ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "46"
        },
        {
            "Job Title": "Staff Software Engineer, iOS",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Full Time",
            "Company Name": "SoFi",
            "Contingency": "No",
            "Location Full": "Remote ; CA-San Francisco ; UT-Other ; WA-Seattle ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "47"
        },
        {
            "Job Title": "Strategic Finance Manager Operations",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Freelance",
            "Company Name": "SoFi",
            "Contingency": "Yes",
            "Location Full": "CA-San Francisco ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Finance",
            "Functional Area Slug": "finance",
            "id": "48"
        },
        {
            "Job Title": "Strategic Finance Senior Associate",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Full Time",
            "Company Name": "SoFi",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Finance",
            "Functional Area Slug": "finance",
            "id": "49"
        },
        {
            "Job Title": "Associate, Capital Management",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Freelance",
            "Company Name": "SoFi",
            "Contingency": "Yes",
            "Location Full": "Remote ; CA-San Francisco ; NY-New York City ; UT-Salt Lake City ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Finance",
            "Functional Area Slug": "finance",
            "id": "50"
        },
        {
            "Job Title": "People Operations Associate",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Freelance",
            "Company Name": "SoFi",
            "Contingency": "Yes",
            "Location Full": "UT-Salt Lake City ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Junior Level",
            "Seniority slug": "entry-level",
            "Functional Area": "Human Resources",
            "Functional Area Slug": "human-resources",
            "id": "51"
        },
        {
            "Job Title": "Privacy Manager",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Full Time",
            "Company Name": "SoFi",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "Legal",
            "Functional Area Slug": "legal",
            "id": "52"
        },
        {
            "Job Title": "Collections Associate - Credit Card",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Internship",
            "Company Name": "SoFi",
            "Contingency": "No",
            "Location Full": "FL-Other ; UT-Salt Lake City ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Junior Level",
            "Seniority slug": "entry-level",
            "Functional Area": "Operations",
            "Functional Area Slug": "operations",
            "id": "53"
        },
        {
            "Job Title": "Facilities and Real Estate Manager",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Full Time",
            "Company Name": "SoFi",
            "Contingency": "No",
            "Location Full": "CA-San Francisco ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "Operations",
            "Functional Area Slug": "operations",
            "id": "54"
        },
        {
            "Job Title": "Manager, Fraud Investigations",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Full Time",
            "Company Name": "SoFi",
            "Contingency": "No",
            "Location Full": "CA-Other ; FL-Other ; TX-Dallas ; UT-Salt Lake City ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "Operations",
            "Functional Area Slug": "operations",
            "id": "55"
        },
        {
            "Job Title": "Member Service Representative- SoFi Money",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Internship",
            "Company Name": "SoFi",
            "Contingency": "No",
            "Location Full": "FL-Other ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Junior Level",
            "Seniority slug": "entry-level",
            "Functional Area": "Operations",
            "Functional Area Slug": "operations",
            "id": "56"
        },
        {
            "Job Title": "Senior Business Operations Analyst",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Full Time",
            "Company Name": "SoFi",
            "Contingency": "No",
            "Location Full": "FL-Other ; UT-Salt Lake City ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Junior Level",
            "Seniority slug": "entry-level",
            "Functional Area": "Operations",
            "Functional Area Slug": "operations",
            "id": "57"
        },
        {
            "Job Title": "Principal Product Manager, SoFi Bank",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Freelance",
            "Company Name": "SoFi",
            "Contingency": "Yes",
            "Location Full": "CA-San Francisco ; UT-Salt Lake City ; WA-Seattle ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Product",
            "Functional Area Slug": "product",
            "id": "58"
        },
        {
            "Job Title": "Senior Product Manager, Invest",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Freelance",
            "Company Name": "SoFi",
            "Contingency": "Yes",
            "Location Full": "Remote ; CA-San Francisco ; NY-New York City ; UT-Salt Lake City ; WA-Seattle ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "Product",
            "Functional Area Slug": "product",
            "id": "59"
        },
        {
            "Job Title": "Credit Risk Manager, Risk Management – Credit Card",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Full Time",
            "Company Name": "SoFi",
            "Contingency": "No",
            "Location Full": "FL-Other ; TX-Dallas ; UT-Salt Lake City ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "60"
        },
        {
            "Job Title": "Senior Risk Data Analyst, Fraud Prevention",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Full Time",
            "Company Name": "SoFi",
            "Contingency": "No",
            "Location Full": "Remote ; CA-San Francisco ; NY-New York City ; TX-Dallas ;",
            "URL": "http://www.sofi.com/careers",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Junior Level",
            "Seniority slug": "entry-level",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "61"
        },
        {
            "Job Title": "Mobile App Product Manager",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Full Time",
            "Company Name": "Common Sense Media",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "http://www.commonsensemedia.org",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "62"
        },
        {
            "Job Title": "Senior Software Engineer (Java)",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Full Time",
            "Company Name": "Charles Schwab",
            "Contingency": "No",
            "Location Full": "TX-Dallas ;",
            "URL": "https://jobs.schwabjobs.com/",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "63"
        },
        {
            "Job Title": ".NET Developer III",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Full Time",
            "Company Name": "Charles Schwab",
            "Contingency": "No",
            "Location Full": "TX-Dallas ;",
            "URL": "https://jobs.schwabjobs.com/",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "64"
        },
        {
            "Job Title": "Salesforce Developer",
            "Time": "2 weeks ago",
            "Date Published": "9/19/22",
            "Job Type": "Temporary",
            "Company Name": "Charles Schwab",
            "Contingency": "Yes",
            "Location Full": "AZ-Phoenix ; NE-Omaha ; TX-Austin ; TX-Dallas ;",
            "URL": "https://jobs.schwabjobs.com/",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "65"
        },
        {
            "Job Title": "Senior Sales Manager, Mexico",
            "Time": "2 weeks ago",
            "Date Published": "9/16/22",
            "Job Type": "Internship",
            "Company Name": "Sonos",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://www.sonos.com/en-us/life-at-sonos",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Sales",
            "Functional Area Slug": "sales",
            "id": "66"
        },
        {
            "Job Title": "Senior Director Product Management",
            "Time": "2 weeks ago",
            "Date Published": "9/16/22",
            "Job Type": "Full Time",
            "Company Name": "The Home Depot",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "http://careers.homedepot.com/technology",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Product",
            "Functional Area Slug": "product",
            "id": "67"
        },
        {
            "Job Title": "Senior QA Engineer",
            "Time": "2 weeks ago",
            "Date Published": "9/16/22",
            "Job Type": "Freelance",
            "Company Name": "Sovos",
            "Contingency": "Yes",
            "Location Full": "MA-Other ;",
            "URL": "https://hrbrg.co/gpi756",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "68"
        },
        {
            "Job Title": "Senior Project Manager (Communications)",
            "Time": "3 weeks ago",
            "Date Published": "9/15/22",
            "Job Type": "Temporary",
            "Company Name": "Wikimedia Foundation",
            "Contingency": "Yes",
            "Location Full": "Remote ;",
            "URL": "https://wikimediafoundation.org/",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Project Management",
            "Functional Area Slug": "project-management",
            "id": "69"
        },
        {
            "Job Title": "Software Engineer III - .NET",
            "Time": "3 weeks ago",
            "Date Published": "9/15/22",
            "Job Type": "Freelance",
            "Company Name": "Sovos",
            "Contingency": "Yes",
            "Location Full": "MN-Other ;",
            "URL": "https://hrbrg.co/gpi756",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "70"
        },
        {
            "Job Title": "Manager, UX",
            "Time": "3 weeks ago",
            "Date Published": "9/15/22",
            "Job Type": "Full Time",
            "Company Name": "Sovos",
            "Contingency": "No",
            "Location Full": "GA-Atlanta ;",
            "URL": "https://hrbrg.co/gpi756",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "71"
        },
        {
            "Job Title": "Sr. Product Manager",
            "Time": "3 weeks ago",
            "Date Published": "9/15/22",
            "Job Type": "Temporary",
            "Company Name": "The Home Depot",
            "Contingency": "Yes",
            "Location Full": "Remote ;",
            "URL": "http://careers.homedepot.com/technology",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Product",
            "Functional Area Slug": "product",
            "id": "72"
        },
        {
            "Job Title": "Product Manager",
            "Time": "3 weeks ago",
            "Date Published": "9/15/22",
            "Job Type": "Temporary",
            "Company Name": "The Home Depot",
            "Contingency": "Yes",
            "Location Full": "Remote ;",
            "URL": "http://careers.homedepot.com/technology",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;",
            "Seniority": "Junior Level",
            "Seniority slug": "entry-level",
            "Functional Area": "Product",
            "Functional Area Slug": "product",
            "id": "73"
        },
        {
            "Job Title": "Staff Systems Engineer",
            "Time": "3 weeks ago",
            "Date Published": "9/15/22",
            "Job Type": "Internship",
            "Company Name": "The Home Depot",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "http://careers.homedepot.com/technology",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "74"
        },
        {
            "Job Title": "Sr. Systems Engineer",
            "Time": "3 weeks ago",
            "Date Published": "9/15/22",
            "Job Type": "Full Time",
            "Company Name": "The Home Depot",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "http://careers.homedepot.com/technology",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "75"
        },
        {
            "Job Title": "Sr. User Experience Designers",
            "Time": "3 weeks ago",
            "Date Published": "9/15/22",
            "Job Type": "Freelance",
            "Company Name": "The Home Depot",
            "Contingency": "Yes",
            "Location Full": "Remote ;",
            "URL": "http://careers.homedepot.com/technology",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Design",
            "Functional Area Slug": "design",
            "id": "76"
        },
        {
            "Job Title": "Principal Software Engineer",
            "Time": "3 weeks ago",
            "Date Published": "9/15/22",
            "Job Type": "Internship",
            "Company Name": "The Home Depot",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "http://careers.homedepot.com/technology",
            "Perks": "remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "77"
        },
        {
            "Job Title": "Nonprofit Success Manager",
            "Time": "3 weeks ago",
            "Date Published": "9/14/22",
            "Job Type": "Full Time",
            "Company Name": "Community First Foundation",
            "Contingency": "No",
            "Location Full": "Hybrid ; CO-Denver ;",
            "URL": "https://www.communityfirstfoundation.org/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Support",
            "Functional Area Slug": "support",
            "id": "78"
        },
        {
            "Job Title": "Lead Data Engineer",
            "Time": "3 weeks ago",
            "Date Published": "9/14/22",
            "Job Type": "Freelance",
            "Company Name": "New Relic",
            "Contingency": "Yes",
            "Location Full": "Remote ;",
            "URL": "https://newrelic.com/",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Other",
            "Functional Area Slug": "zother",
            "id": "79"
        },
        {
            "Job Title": "Senior Frontend Software Engineer - (Remote)",
            "Time": "3 weeks ago",
            "Date Published": "9/14/22",
            "Job Type": "Full Time",
            "Company Name": "New Relic",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://newrelic.com/",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "80"
        },
        {
            "Job Title": "Senior Product Designer",
            "Time": "3 weeks ago",
            "Date Published": "9/14/22",
            "Job Type": "Full Time",
            "Company Name": "Chronosphere",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://chronosphere.io/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Product",
            "Functional Area Slug": "product",
            "id": "81"
        },
        {
            "Job Title": "Senior Technical Writer",
            "Time": "3 weeks ago",
            "Date Published": "9/14/22",
            "Job Type": "Temporary",
            "Company Name": "Chronosphere",
            "Contingency": "Yes",
            "Location Full": "Remote ;",
            "URL": "https://chronosphere.io/",
            "Seniority": "Junior Level",
            "Seniority slug": "entry-level",
            "Functional Area": "Product",
            "Functional Area Slug": "product",
            "id": "82"
        },
        {
            "Job Title": "Customer Solutions Engineer",
            "Time": "3 weeks ago",
            "Date Published": "9/14/22",
            "Job Type": "Full Time",
            "Company Name": "Chronosphere",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://chronosphere.io/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Other",
            "Functional Area Slug": "zother",
            "id": "83"
        },
        {
            "Job Title": "Senior Software Engineer - Frontend",
            "Time": "3 weeks ago",
            "Date Published": "9/14/22",
            "Job Type": "Freelance",
            "Company Name": "Chronosphere",
            "Contingency": "Yes",
            "Location Full": "Remote ;",
            "URL": "https://chronosphere.io/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "84"
        },
        {
            "Job Title": "Head of Corporate Communications",
            "Time": "3 weeks ago",
            "Date Published": "9/14/22",
            "Job Type": "Full Time",
            "Company Name": "Chronosphere",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://chronosphere.io/",
            "Seniority": "Management",
            "Seniority slug": "z-management",
            "Functional Area": "Marketing",
            "Functional Area Slug": "marketing",
            "id": "85"
        },
        {
            "Job Title": "Technical Content Writer",
            "Time": "3 weeks ago",
            "Date Published": "9/14/22",
            "Job Type": "Full Time",
            "Company Name": "Chronosphere",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://chronosphere.io/",
            "Seniority": "Junior Level",
            "Seniority slug": "entry-level",
            "Functional Area": "Marketing",
            "Functional Area Slug": "marketing",
            "id": "86"
        },
        {
            "Job Title": "Aspire Program – Tech Careers for Women",
            "Time": "3 weeks ago",
            "Date Published": "9/14/22",
            "Job Type": "Full Time",
            "Company Name": "Wiley Edge",
            "Contingency": "No",
            "Location Full": "NY-New York City ;",
            "URL": "https://www.wileyedge.com",
            "Seniority": "Junior Level",
            "Seniority slug": "entry-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "87"
        },
        {
            "Job Title": "Sr Manager GTM G&A Talent Team",
            "Time": "3 weeks ago",
            "Date Published": "9/14/22",
            "Job Type": "Full Time",
            "Company Name": "Chronosphere",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://chronosphere.io/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "People Ops",
            "Functional Area Slug": "people-ops",
            "id": "88"
        },
        {
            "Job Title": "Workplace Experience Manager",
            "Time": "3 weeks ago",
            "Date Published": "9/14/22",
            "Job Type": "Freelance",
            "Company Name": "Chronosphere",
            "Contingency": "Yes",
            "Location Full": "NY-New York City ;",
            "URL": "https://chronosphere.io/",
            "Seniority": "Junior Level",
            "Seniority slug": "entry-level",
            "Functional Area": "People Ops",
            "Functional Area Slug": "people-ops",
            "id": "89"
        },
        {
            "Job Title": "Lead Software Engineer - Identity (Remote)",
            "Time": "3 weeks ago",
            "Date Published": "9/13/22",
            "Job Type": "Full Time",
            "Company Name": "Black Rock",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://newrelic.com/",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "90"
        },
        {
            "Job Title": "DevOps Engineer",
            "Time": "3 weeks ago",
            "Date Published": "9/13/22",
            "Job Type": "Internship",
            "Company Name": "iZotope",
            "Contingency": "No",
            "Location Full": "MA-Boston ;",
            "URL": "http://izotope.com",
            "Perks": "remotefriendly ; unlimitedvacation ; paidparentalleave ;",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "91"
        },
        {
            "Job Title": "Sr Manager, App Dev",
            "Time": "3 weeks ago",
            "Date Published": "9/13/22",
            "Job Type": "Internship",
            "Company Name": "Federal Reserve Bank of San Francisco",
            "Contingency": "No",
            "Location Full": "CA-San Francisco ;",
            "URL": "https://www.frbsf.org/our-district/careers/",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "92"
        },
        {
            "Job Title": "Sr. Solution Architect",
            "Time": "3 weeks ago",
            "Date Published": "9/13/22",
            "Job Type": "Full Time",
            "Company Name": "Federal Reserve Bank of San Francisco",
            "Contingency": "No",
            "Location Full": "CA-San Francisco ;",
            "URL": "https://www.frbsf.org/our-district/careers/",
            "Seniority": "Senior Level",
            "Seniority slug": "senior-level",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "93"
        },
        {
            "Job Title": "Lead DevOps Engineer",
            "Time": "3 weeks ago",
            "Date Published": "9/13/22",
            "Job Type": "Full Time",
            "Company Name": "Federal Reserve Bank of San Francisco",
            "Contingency": "No",
            "Location Full": "CA-San Francisco ;",
            "URL": "https://www.frbsf.org/our-district/careers/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "IT & Cybersecurity",
            "Functional Area Slug": "it-cybersecurity",
            "id": "94"
        },
        {
            "Job Title": "Senior Software Engineer",
            "Time": "3 weeks ago",
            "Date Published": "9/13/22",
            "Job Type": "Internship",
            "Company Name": "Asana",
            "Contingency": "No",
            "Location Full": "IL-Chicago ;",
            "URL": "https://www.mcmaster.com/careers",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "95"
        },
        {
            "Job Title": "Data Center Engineer (contract, part-time)",
            "Time": "3 weeks ago",
            "Date Published": "9/12/22",
            "Job Type": "Full Time",
            "Company Name": "Wikimedia Foundation",
            "Contingency": "No",
            "Location Full": "TX-Other ;",
            "URL": "https://wikimediafoundation.org/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "96"
        },
        {
            "Job Title": "Integrated Marketing Specialist",
            "Time": "3 weeks ago",
            "Date Published": "9/12/22",
            "Job Type": "Full Time",
            "Company Name": "Wikimedia Foundation",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://wikimediafoundation.org/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Marketing",
            "Functional Area Slug": "marketing",
            "id": "97"
        },
        {
            "Job Title": "Legal Fellow (Spring 2023)",
            "Time": "3 weeks ago",
            "Date Published": "9/12/22",
            "Job Type": "Full Time",
            "Company Name": "Wikimedia Foundation",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://wikimediafoundation.org/",
            "Seniority": "Junior Level",
            "Seniority slug": "entry-level",
            "Functional Area": "Legal",
            "Functional Area Slug": "legal",
            "id": "98"
        },
        {
            "Job Title": "Senior Software Engineer - Platform",
            "Time": "3 weeks ago",
            "Date Published": "9/12/22",
            "Job Type": "Full Time",
            "Company Name": "Chronosphere",
            "Contingency": "No",
            "Location Full": "Remote ;",
            "URL": "https://chronosphere.io/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering",
            "id": "99"
        },
        {
            "Job Title": "Senior Software Engineer - Infrastructure",
            "Time": "3 weeks ago",
            "Date Published": "9/12/22",
            "Job Type": "Freelance",
            "Company Name": "Chronosphere",
            "Contingency": "Yes",
            "Location Full": "Remote ;",
            "URL": "https://chronosphere.io/",
            "Seniority": "Mid Level",
            "Seniority slug": "mid-level",
            "Functional Area": "Engineering",
            "Functional Area Slug": "engineering***",
            "id": "100"
        }
    ]




    export default jobData;